
package com.training.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MovieService", targetNamespace = "http://ifaces.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRating", targetNamespace = "http://ifaces.training.com/", className = "com.training.example.GetRating")
    @ResponseWrapper(localName = "getRatingResponse", targetNamespace = "http://ifaces.training.com/", className = "com.training.example.GetRatingResponse")
    @Action(input = "http://ifaces.training.com/MovieService/getRatingRequest", output = "http://ifaces.training.com/MovieService/getRatingResponse")
    public double getRating(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
